---
- name: apply or delete kubernetes manifest file 
  hosts: localhost
  tasks: 
     - name: apply manifest file
       command: "kubectl --kubeconfig=$PWD/04_ansible/kubeconfig/kubeconfig-k3s.yml apply -k ~/bootcamp-devops-projet/03_kubernetes"

    #- name: apply manifest file
    #  command: "kubectl --kubeconfig=../kubeconfig/kubeconfig-k3s.yml delete -k ~/bootcamp-devops-projet/03_kubernetes"





