---
- name: retrieve kubeconfig file 
  hosts: k3s 
  tasks: 
    - name: copy file kubeconfig 
      fetch: 
        src: /etc/rancher/k3s/k3s.yaml
        dest: $PWD/04_ansible/kubeconfig/kubeconfig
        flat: yes
    - name: modify kubeconfig file 
      local_action: 
        module: lineinfile
        path: $PWD/04_ansible/kubeconfig/kubeconfig
        regexp: '^   server: https://127.0.0.1:6443'
        line: '^   server: https://{{ ansible_host }}:6443'

